config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :users
  # plus la peine d'avoir le controller user si pas de nesting (car déjà devise)

  resources :psychics, only: [:index, :show, :create, :new, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
    resources :accessories
  end

  resources :bookings, only: [:show, :edit, :update]
  get 'dashboard', to: 'users#dashboard'
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  ACCESS = %w[CrystalBall MagicTea Van Cat Ghost AK47 Cards OuijaBoard]

  belongs_to :psychic, optional: true
  validates :name, :price, presence: true
  validates :price, numericality: { only_integer: true }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :psychic

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/psychic.rb
class Psychic < ApplicationRecord
  SPEC = %w[blackMagic Voodoo KarmaBooster Visions Ghosts Tarot Divination AstralProjection EnergyMedicine]
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :accessories, dependent: :destroy
  has_one_attached :photo
  validates :localisation, :hour_rate, :specialty, presence: true

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [:specialty, :localisation],
      associated_against: {user: [:name, :last_name], accessories: [:name]},
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_one :psychic
  has_many :psychics, through: :bookings

  validates :name, :last_name, :email, presence: true
  validates :email, uniqueness: true
end

app/controllers/accessories_controller.rb
class AccessoriesController < ApplicationController
  before_action :set_psychic, only: [ :new, :create ]
  def show
  end

  def new
  	@accessory = Accessory.new
  end

  def create
    @accessory = Accessory.new(accessory_params)
    @accessory.psychic = @psychic

    if @accessory.save
    	redirect_to psychic_path(@psychic)
    else
    	redirect_to psychic_path(@psychic), notice: 'Please try again'
    end
  end

  private
  
  def set_psychic
    @psychic = Psychic.find(params[:psychic_id])
  end

  def accessory_params
    params.require(:accessory).permit(:name, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name])
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :find_booking, only: [ :show ]
  before_action :set_psychic, only: [ :new, :create ]

  def new
    # creer un nouveau booking en tant que user
    @booking = Booking.new
  end

  def create
    # creer un nouveau booking en tant que user
    # a la con
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.psychic_id = @psychic.id

    if @booking.save
      redirect_to booking_path(@booking)
    else
      render :new
      # redirect_to psychic_path(@psychic), notice: "Sorry, incorrect book form. Please try again!"
    end
  end

  def show
    # montrer le booking pour voir les infos et le statut
  end

  def edit
    # seulement pour le user qui possede le FT du booking --> accepter ou refuser le booking
    # default: pending, accepted/declined
  end

  def update
    # seulement pour le user qui possede le FT du booking --> accepter ou refuser le booking
    # default: pending, accepted/declined
    # question --> comment on pourrait faire pour faire deux methodes de type update sur 2 champs different
    #   par exemple si le FT peut updater le statut et le user updater la date du booking?
  end

  def delete

  end

  private

  def find_booking
    @booking = Booking.find(params[:id])
  end

  def set_psychic
    @psychic = Psychic.find(params[:psychic_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :nb_accessories, :total_price)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/psychics_controller.rb
class PsychicsController < ApplicationController

  before_action :find_psychic, only: [ :show, :edit, :update, :destroy ]

  def index
    if params[:query].present?
      # les lignes commentees c'est pour faire en sql et pas en pgsearch
      # sql_query = " \
      #   psychics.specialty ILIKE :query \
      #   OR psychics.localisation ILIKE :query \
      #   OR accessories.name ILIKE :query \
      #   OR users.name ILIKE :query \
      # "
      # @psychics = Psychic.joins(:user).where(sql_query, query: "%#{params[:query]}%")
      @psychics = Psychic.global_search(params[:query])
    else
      @psychics = Psychic.all
    end
  end

  def new
  	@psychic = Psychic.new
  end

  def create
  	@psychic = Psychic.new(psychic_params)
  	@psychic.user = current_user

  	if @psychic.save
  	  redirect_to @psychic, notice: 'Psychic profile was successfuly completed'
  	else
  	  render :new
  	end
  end

  def show
    @accessory = Accessory.new
    @booking = Booking.new
  end


  def edit
  end

  def update
    @psychic.update(psychic_params)
    if @psychic.save
      redirect_to @psychic, notice: 'Psychic profile was successfuly edited'
    else
      render :edit
    end
  end

  def destroy
    @psychic.destroy
    redirect_to psychics_path
  end

  private

  def find_psychic
  @psychic = Psychic.find(params[:id])
  end

  def psychic_params
    params.require(:psychic).permit(:specialty, :localisation, :hour_rate, :photo)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @user = current_user
    @bookings = @user.bookings
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
<div id="confirmation-container" class="text-center">

  <div class="first-info">

  <h1>Thank you!</h1>
  <h2>You successfully sent a booking request to:<br>
  	<% psychic = Psychic.find(@booking.psychic_id) %>
  	<%= User.find(psychic.user_id).name %>
  	(specialty: <%= psychic.specialty %>)
   </h2>
   <%= image_tag 'sparkles.png' %>
  </div>
   <div class="infos-list">
    <ul>
      <li>Start date: <%= @booking.start_date %></li>
      <li>End date: <%= @booking.end_date %></li>
      <li>Accessories:
      <% if @booking.nb_accessories != nil %>
        <% @booking.nb_accessories%>
      <% else %>
      0
      <% end %>
      </li>
      <li>Total price: <%= @booking.total_price %>€</li>
      <li> Status:<div class="status"><%= @booking.status%></div></li>
    </ul>
   </div>

  <p>Your booking is now pending. <%= User.find(psychic.user_id).name%> must confirm it before any payment.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAPsychic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload', defer: true %>


  </head>

  <body id="<%= 'background-dark' if controller_name == 'psychics' &&  action_name == 'index'%>">

    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

  <!--   <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="bg">
  <div class="hp-container">
    <h2>Rent a Psychic</h2>
    <div class="index-link"> <%= link_to 'book your psychic', psychics_path %></div>
    <%= image_tag 'crystal-ball-hp.png' %>
  </div>
</div>

<div class="home-container p-4">

  <div class="container p-3" style="border: solid 1px lightgrey; border-radius: 5px;">
    <div class="row">
      <div class="col-12 col-lg-8">
        <div class="infos">
          <h3>Who are we?</h3>
          <p>Rent a Psychic is the leading marketplace of fortune teller, psychic and wizzard rental for all your events/parties/orgies/curse you want to set up. We make sure that we you can find the right service at the right time and at the right price in a simple way. Book your psychics NOW !!!</p>
        </div>
      </div>
      <div class="col-12 col-lg-4 d-flex justify-content-center">
        <img src="https://media.giphy.com/media/8FxtdFhCKXLFTWkX1H/giphy.gif" alt="funny gif" class="img-gif">
      </div>
    </div>
  </div>

<div class="container p-3 mt-4 mb-3" style="border: solid 1px white; border-radius: 5px;">
    <div class="row">
      <div class="col-12 col-lg-8">
        <div class="infos">
          <h3>What can you book on Rent a Psychic?</h3>
          <p>On the platform you can book any time of service (but we don't want to know about anything illegal, including murder, voodoo or memory theft).Please note that we don't garantee any unfortunate event on our beloved customers in case of frog transformation or ghots invasion.</p>
        </div>
      </div>
      <div class="col-12 col-lg-4 d-flex justify-content-center">
        <img src="https://media.giphy.com/media/xT1XGx85kYUIFWI4wg/giphy.gif" alt="funny gif" class="img-gif">
      </div>
    </div>
  </div>
</div>

<!--  <div class="d-flex gif-box">
      <img src="https://media.giphy.com/media/xT1XGx85kYUIFWI4wg/giphy.gif" alt="funny gif" class="rounded img-gif">
      <img src="https://media.giphy.com/media/8FxtdFhCKXLFTWkX1H/giphy.gif" alt="funny gif" class="rounded img-gif">
    </div>
  </div> -->




<!-- <img src="https://media.giphy.com/media/l2JJu8U8SoHhQEnoQ/giphy.gif">

<img src="https://media.giphy.com/media/dw2yCF4MhcNmSMgpfe/giphy.gif"> -->

<!-- <div class="service-info container">
  <h3>Who are we?</h3>
  <p>
    <strong> Rent a Psychic </strong> is the leading marketplace of fortune teller, psychic and wizzard rental for all your events/parties/orgies/curse you want to set up.
    We make sure that we you can find the right service at the right time and at the right price in a simple way.
    <br> Book your psychics NOW !!!
  </p>
  <h3>What can you book on <strong> Rent a Psychic </strong> </h3>
  <p>
    On the platform you can book any time of service (but we don't want to know about anything illegal, including murder, voodoo or memory theft).
    <br><span>Please note that we don't garantee any unfortunate event on our beloved customers in case of frog transformation or ghots invasion.</span>
  </p> -->

app/views/psychics/edit.html.erb
<div class="edit-form-container">

  <div id="add-form" class="d-flex justify-content-center">
    <div id='edit-psychic-profile'>
        <h1>Modify your profile anytime here:</h1>
      <div class="d-flex justify-content-center">
      	<div id='edit-form'>
          <%= simple_form_for(@psychic) do |f| %>
            <%= f.input :specialty, collection: Psychic::SPEC, prompt: "Select your specialty" %>
            <%= f.input :hour_rate, as: :numeric, placeholder: 'Enter your price per hour (in €)'%>
            <%= f.input :localisation, as: :string, placeholder: 'Precise your address' %>
            <%= f.input :photo, as: :file %>
            <%= f.submit "Create your psychic profile", class: "btn btn-flat" %>
          <% end %>
      	 </div>
      </div>
  </div>
</div>
</div>

app/views/psychics/index.html.erb
<div id="half-fold-purple" class="d-flex flex-column justify-content-center align-items-center">
  <div><h1> Here are all our great psychics !</h1></div>
  <div><h2>Have a look to find the one who will bring you some magic...</h2></div>
  <div class="d-flex" id="search-form">
  <%= form_tag psychics_path, method: :get do %>
    <%= submit_tag "Search", class: "btn btn-primary", id:"search-submit" %>
    <%= text_field_tag :query, params[:query], class: "form-control", id: "search-input", placeholder: "Find a psychic" %>
  </div>
<% end %>
</div>

<div class="container">

    <div style="margin-top: -70px">
      <div class="cards">
        <% @psychics.each do |psychic| %>
            <div class="card-index">
              <%= link_to psychic_path(psychic) do %>
                <% if psychic.photo.attached? %>
                  <%= cl_image_tag psychic.photo.key, crop: :pad %>
                <% else %>
                  <img src='https://source.unsplash.com/1600x900/?photos,portrait'/>
                <% end %>
                <div class="card-int">
                  <h3><%= psychic.user.name%> <%= psychic.user.last_name%></h3>
                  <p><i class="fas fa-map-marker-alt"></i> <%= psychic.localisation %></p>
                  <div class='d-flex justify-content-end'>
                    <div>
                      <p><strong>€<%= psychic.hour_rate %></strong>/hour</p>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
        <% end %>
      </div>
    </div>
</div>

app/views/psychics/new.html.erb
<div class="psychic-form-container">


<h1>Interested in renting your precious psychic powers? Join us!</h1>
  <div id="add-form" class="d-flex justify-content-center">
    <div id='new-psychic-profile'>
       <%= simple_form_for(@psychic) do |f| %>
          <%= f.input :specialty, collection: Psychic::SPEC, label:false, prompt: "Select your specialty" %>
         <!--  <=%= f.input :specialty, as: :string, label: false, type: :text, placeholder: 'Precise your specialty' %> -->
          <%= f.input :hour_rate, as: :numeric, label: false, placeholder: 'Enter your price per hour (in €)'%>
          <%= f.input :localisation, as: :string, label: false, placeholder: 'Precise your address' %>
          <%= f.input :photo, as: :file %>
          <%= f.submit "Create your psychic profile", class: "btn btn-flat" %>
       <% end %>
       </div>
  </div>
</div>

app/views/psychics/show.html.erb
<!-- Card of the page : information about psychic -->

<div class="psychic-container">
  <div class="card-product">
    <% if @psychic.photo.attached? %>
        <%= cl_image_tag @psychic.photo.key, width: 400, height: 300, crop: :pad %>
        <% else %>
        <img src='https://vanbytheriver.files.wordpress.com/2015/06/psychic.jpg'/>
    <% end %>
    <div class="card-product-infos">
      <div class="d-flex flex-row">
        <h2><%= User.find(@psychic.user_id).name %></h2>
        <%= link_to 'go back to psychics', psychics_path, class: "btn btn-flexbox-upper-right", id: "grey-btn"%>
      </div>
        <p>specialzed in: </p> <span class="specialty"><%= @psychic.specialty %><i class="fas fa-hand-sparkles"></i></span>
        <p><i class="fas fa-map-marker-alt"></i> <%= @psychic.localisation %></p>
        <p><strong>€<%= @psychic.hour_rate %></strong>/hour</p>
        <% if @psychic.accessories != [] %>
          <p><strong><%= User.find(@psychic.user_id).name %>'s accessories:</strong></p>
            <% @psychic.accessories.each do |accessory| %>
              <li><%= accessory.name %></li>
            <% end %>
        <% end %>
    </div>
  </div>

<!-- User action -->

  <div class="d-flex justify-content-center">
    <div id="booking-form">
      <% if current_user != nil %>
        <% if current_user.id != @psychic.user_id %>
         <h2>Book <%= User.find(@psychic.user_id).name%> now:</h2>
            <%= simple_form_for([@psychic, @booking]) do |f| %>
              <%= f.input :start_date, as: :string, label: false, type: :text,  placeholder: 'From' %>
<!-- <<<<<<< HEAD
              <=%= f.input :end_date, as: :string, label: false, type: :text,   placeholder: 'To'%>
              <=%= f.input :total_price, as: :integer, input_html: {value: 135 }%>
              <=% if @psychic.accessories != nil %>
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#accessoryBooking">Add accessories to your booking</button>
======= -->
              <%= f.input :end_date, as: :string, label: false, type: :text,   placeholder: 'To'%>
              <%= f.input :total_price, as: :hidden  %>
              <%= f.input :nb_accessories, as: :hidden %>
              <% if @psychic.accessories != [] %>
              <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#accessoryBooking">Add accessories</button>

              <%end%>
              <br>
              <br>
              <div>
              <div>
                <td><span id="price_per_hour"><%= @psychic.hour_rate %></span>€ x <span id="hours">0</span> hours:</td>
                <td><span id="price">0</span>€</td>
                <div class=accessory-display>
                  <td>10€ x <span class="number_accessory">0</span><span class="accessory"> accessory:</span></td>
                  <td><span class="price_accessory">0</span>€</td>
                </div> 
               <br>
              <p class= "total-price">Total Price: <span id="total-price">0</span>€</p> 
              </div>      
              <div>
              <br>
              <%= f.submit "Book", class: "btn btn-flat" %>
              </div>
            <% end %>

            </div>
      <%else%>
            <button type="button" class="btn btn-flat btn-card-show-psychic" data-toggle="modal" data-target="#edit">
            Edit
            </button>
            <button type="button" class="btn btn-flat btn-card-show-psychic" data-toggle="modal" data-target="#addAccessory">
            Add accessories to your profile
            </button>
            <%= link_to "Delete",
            psychic_path(@psychic),
              method: :delete,
              class: "btn btn-flat btn-card-show-psychic"%>
        <%end%>
      <%end%>
    </div>
  </div>
</div>

<!-- MODALS for user action -->


<!-- ADD ACCESSORY - BOOKING -->

<div class="modal fade" id="accessoryBooking" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add accessories to your booking</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
          <div class="modal-body">

              <p> Fixed price per accessory : 10 € </p>
              <div class = "check">
                <% @psychic.accessories.each do |accessory| %>
                  <div class="form-check">
                    <input class="form-check-input" type="checkbox" value="" id="defaultCheck1" remote = "true">
                    <label class="form-check-label" for="defaultCheck1">
                      <%= accessory.name %>
                    </label>
                  </div>
              <%end%>
              <br>
              </div>
              <div id=accessory-display>
                <td>10€ x <span class="number_accessory">0</span><span class="accessory"> accessory:</span></td>
                <td><span class="price_accessory">0</span>€</td>
              </div>
              <br>
              <button type="submit" id="add-accessory" data-dismiss="modal" class="btn btn-sm btn-outline-primary rounded-pill">Add</button>
        </div>
      </div>
    </div>
  </div>

<!-- ADD ACCESSORY - PSYCHIC -->

  <div class="modal fade" id="addAccessory" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add an accessory</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
          <div class="modal-body">
              <%= simple_form_for [@psychic, @accessory] do |f| %>
                <%= f.input :name, collection: Accessory::ACCESS , label:false, prompt: "Select your specialty"%>
                <p> Each accessory has fixed price : 10 € </p>
                <%= f.input :price, as: :hidden, input_html: { value: 10 } %>
                <%= f.submit "Edit", class: "btn btn-sm btn-outline-primary rounded-pill" %>
              <%end%>
        </div>
      </div>
    </div>
  </div>

<!-- EDIT PSYCHIC PROFIL -->

  <div class="modal fade" id="edit" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Edit</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
          <div class="modal-body">
          <%= simple_form_for(@psychic) do |f| %>
            <%= f.input :specialty, as: :string, label: false, type: :text, placeholder: 'Precise your specialty' %>
            <%= f.input :hour_rate, as: :numeric, label: false, placeholder: 'Enter your price per hour'%>
            <%= f.input :localisation, as: :string, label: false, placeholder: 'Precise your city' %>
            <%= f.input :photo, as: :file %>
            <%= f.submit "Edit", class: "btn btn-sm btn-outline-primary rounded-pill" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex flex-column justify-content-around">
  <div>
    <p>Done with magic and <i class="fas fa-heart" style="color: red"></i> by the worst front team ever</p>
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon justify-content-end">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag 'crystal-ball-nav.png' %>
    <% end %>

  <% if user_signed_in? %>
    <% if current_user.psychic.nil? %>
      <%= link_to "Create my psychic profile", new_psychic_path, class: "btn btn-flat m-3" %>
    <% else %>
      <%= link_to "Show my psychic profile", psychic_path(current_user.psychic.id), class: "btn btn-flat m-3" %>
    <% end %>
  <% end %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
         <!--  <=%= link_to "Home", '#', class: "nav-link" %> -->
        </li>
        <li class="nav-item">
          <%= link_to "My dashboard", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="dashboard-bg">

  <div class="intro text-center p-4" style="color:lightgrey;">
    <h1>Hello <%= @user.name %></h1>
    <h2>Here are the current bookings you made for psychics:</h2>
  </div>

  <div class="bookings-container p-4">
    <% @bookings.each do |booking| %>
    <div class="container p-3 mb-3" style="border: solid 1px lightgrey; border-radius: 5px;">
      <div class="row">
        <div class="col-12 col-lg-8">
          <div class="infos">
            <h3><p><%= booking.psychic.user.name %></p></h3>
            <p>Start date: <%= booking.start_date %><p>
            <p>End date: <%= booking.end_date %></p>
            <p>Number of accessories: <%= booking.nb_accessories %></p>
            <p>Total price: €<%= booking.total_price %></p>
          </div>
        </div>
        <div class="col-12 col-lg-4 d-flex justify-content-center">
          <p>Booking status:</p><div class="status"><%=booking.status%></div>
        </div>
      </div>
    </div>
    <% end %>
  </div>

</div>